<?php

namespace Database\Seeders;

use App\Models\Facility;
use Illuminate\Database\Seeder;

class FacilitySeeder extends Seeder
{
    public function run(): void
    {
        $facilities = [
            [
                'slug' => 'guest-houses',
                'title' => 'Sanctuary Guest Houses',
                'category' => 'Guest House',
                'year' => '2018',
                'location' => 'Kibeho, Nyaruguru',
                'managed_by' => 'Kibeho Sanctuary',
                'capacity' => '120 rooms',
                'status' => 'Available',
                'rating' => 4.5,
                'booking_url' => '/contact',
                'featured' => true,
                'short_description' => 'Comfortable accommodation for pilgrims and retreat groups — a place of rest before and after prayer.',
                'description' => '<p>Our guest houses welcome pilgrims from Rwanda and around the world with simple, clean rooms and a spirit of hospitality. Whether you stay one night or a full retreat, our accommodation puts you steps from the shrine and apparition sites.</p>',
                'cover_image' => '/images/sanctuary/welcome.jpg',
                'featured_image' => '/images/sanctuary/welcome.jpg',
                'gallery' => [
                    '/images/sanctuary/welcome.jpg',
                    '/images/sanctuary/hero.jpg',
                    '/images/sanctuary/hills.jpg',
                ],
                'amenities' => [
                    'parking', 'wifi', 'hot-water', 'hill-views', 'restaurant', 'breakfast',
                    'generator', 'security', 'mosquito-nets', 'chapel', 'garden',
                ],
                'related_programs' => ['daily-mass', 'shuttle', 'spiritual-guidance', 'laundry', 'retreats'],
                'specs' => [
                    'Location' => 'Kibeho, Nyaruguru',
                    'Capacity' => '120 rooms',
                    'Category' => 'Guest House',
                    'Managed by' => 'Kibeho Sanctuary',
                    'Check-in' => 'From 2:00 PM',
                    'Status' => 'Available',
                ],
                'sort_order' => 1,
            ],
            [
                'slug' => 'kibeho-hillside-hotel',
                'title' => 'Kibeho Hillside Hotel',
                'category' => 'Hotel',
                'year' => '2020',
                'location' => 'Near Kibeho Sanctuary',
                'managed_by' => 'Private partner',
                'capacity' => '45 rooms',
                'status' => 'Available',
                'rating' => 4.0,
                'booking_url' => '/contact',
                'website_url' => '',
                'phone' => '+250 788 123 456',
                'whatsapp' => '+250788123456',
                'email' => 'info@kibehosanctuary.org',
                'featured' => true,
                'short_description' => 'Hotel stays with easy access to the shrine for pilgrims and visitors.',
                'description' => '<p>A welcoming hotel near the sanctuary grounds, suited for pilgrims seeking comfortable rooms close to daily Mass and shrine activities.</p>',
                'cover_image' => '/images/sanctuary/hero.jpg',
                'featured_image' => '/images/sanctuary/hero.jpg',
                'gallery' => [
                    '/images/sanctuary/hero.jpg',
                    '/images/sanctuary/welcome.jpg',
                    '/images/sanctuary/hills.jpg',
                    '/images/projects/grand-legacy-hotel-interior/gallery-1.jpg',
                ],
                'amenities' => [
                    'parking', 'wifi', 'hot-water', 'hill-views', 'swimming-pool', 'bar',
                    'table-tennis', 'restaurant', 'air-conditioning', 'conference', 'breakfast', 'security',
                ],
                'related_programs' => ['daily-mass', 'shuttle', 'guided-tours', 'laundry'],
                'specs' => [
                    'Location' => 'Near Kibeho Sanctuary',
                    'Category' => 'Hotel',
                    'Status' => 'Available',
                ],
                'sort_order' => 2,
            ],
            [
                'slug' => 'pilgrim-apartments',
                'title' => 'Pilgrim Apartments',
                'category' => 'Apartment',
                'year' => '2022',
                'location' => 'Kibeho centre',
                'managed_by' => 'Local hosts',
                'capacity' => '18 units',
                'status' => 'Available',
                'rating' => 3.5,
                'booking_url' => '/contact',
                'featured' => false,
                'short_description' => 'Self-catering apartments for families and longer pilgrimage stays.',
                'description' => '<p>Furnished apartments for families and groups who prefer a home-like stay during their pilgrimage.</p>',
                'cover_image' => '/images/sanctuary/hills.jpg',
                'featured_image' => '/images/sanctuary/hills.jpg',
                'gallery' => ['/images/sanctuary/hills.jpg', '/images/sanctuary/welcome.jpg'],
                'amenities' => [
                    'parking', 'wifi', 'hot-water', 'hill-views', 'kitchenette', 'family-rooms', 'security',
                ],
                'related_programs' => ['laundry', 'airport-pickup'],
                'specs' => [
                    'Location' => 'Kibeho centre',
                    'Category' => 'Apartment',
                    'Status' => 'Available',
                ],
                'sort_order' => 3,
            ],
            [
                'slug' => 'marian-retreat-house',
                'title' => 'Marian Retreat House',
                'category' => 'Guest House',
                'year' => '2015',
                'location' => 'Kibeho, Nyaruguru',
                'managed_by' => 'Diocese of Gikongoro',
                'capacity' => '60 beds',
                'status' => 'Available',
                'rating' => 4.2,
                'booking_url' => '/contact',
                'featured' => true,
                'short_description' => 'Quiet retreat lodging for prayer groups and spiritual weekends.',
                'description' => '<p>A peaceful guest house oriented toward retreats, silence, and communal prayer near the shrine.</p>',
                'cover_image' => '/images/sanctuary/mary.jpg',
                'featured_image' => '/images/sanctuary/mary.jpg',
                'gallery' => ['/images/sanctuary/mary.jpg', '/images/sanctuary/hills.jpg'],
                'amenities' => [
                    'parking', 'wifi', 'hot-water', 'hill-views', 'chapel', 'garden', 'generator', 'breakfast',
                ],
                'related_programs' => ['daily-mass', 'spiritual-guidance', 'retreats', 'laundry'],
                'specs' => [
                    'Location' => 'Kibeho, Nyaruguru',
                    'Category' => 'Guest House',
                    'Status' => 'Available',
                ],
                'sort_order' => 4,
            ],
            [
                'slug' => 'chapel-shrine',
                'title' => 'Chapel & Shrine',
                'category' => 'Worship',
                'year' => '2003',
                'location' => 'Kibeho, Nyaruguru',
                'managed_by' => 'Diocese of Gikongoro',
                'capacity' => 'Main sanctuary',
                'status' => 'Open Daily',
                'featured' => false,
                'short_description' => 'The heart of Kibeho — where Holy Mass, adoration, and pilgrim devotions take place throughout the day.',
                'description' => '<p>The shrine chapel is the spiritual center of Kibeho Sanctuary. Here pilgrims gather for daily Mass, Eucharistic adoration, and the Rosary — in the shadow of the apparition hill where Our Lady appeared to the visionaries.</p>',
                'cover_image' => '/images/projects/nyarutarama-residence/cover.jpg',
                'featured_image' => '/images/projects/nyarutarama-residence/featured.jpg',
                'gallery' => ['/images/projects/nyarutarama-residence/gallery-1.jpg'],
                'related_programs' => ['Holy Mass', 'Adoration', 'Rosary'],
                'specs' => [
                    'Location' => 'Kibeho, Nyaruguru',
                    'Category' => 'Worship',
                    'Capacity' => '2,000+ seated',
                    'Managed by' => 'Diocese of Gikongoro',
                    'Hours' => 'Open daily',
                    'Status' => 'Open Daily',
                ],
                'sort_order' => 10,
            ],
            [
                'slug' => 'dining',
                'title' => 'Dining Hall',
                'category' => 'Dining',
                'year' => '2016',
                'location' => 'Kibeho, Nyaruguru',
                'managed_by' => 'Kibeho Sanctuary',
                'capacity' => '350 seats',
                'status' => 'Available',
                'featured' => false,
                'short_description' => 'Shared meals for pilgrims and groups — simple, nourishing food served in a spirit of community.',
                'description' => '<p>The dining hall serves breakfast, lunch, and dinner for resident pilgrims and day visitors. Group meals can be arranged in advance for parish pilgrimages and retreat programs.</p>',
                'cover_image' => '/images/projects/grand-legacy-hotel-interior/cover.jpg',
                'featured_image' => '/images/projects/grand-legacy-hotel-interior/featured.jpg',
                'gallery' => ['/images/projects/grand-legacy-hotel-interior/gallery-1.jpg'],
                'related_programs' => ['Retreats'],
                'specs' => [
                    'Location' => 'Kibeho, Nyaruguru',
                    'Capacity' => '350 seats',
                    'Category' => 'Dining',
                    'Meals' => 'Breakfast, lunch, dinner',
                    'Group booking' => 'By arrangement',
                    'Status' => 'Available',
                ],
                'sort_order' => 3,
            ],
            [
                'slug' => 'souvenir-shop',
                'title' => 'Souvenir Shop',
                'category' => 'Services',
                'year' => '2010',
                'location' => 'Kibeho, Nyaruguru',
                'managed_by' => 'Kibeho Sanctuary',
                'capacity' => 'Ground floor',
                'status' => 'Open Daily',
                'featured' => false,
                'short_description' => 'Rosaries, medals, books, and devotional items to carry the grace of Kibeho home with you.',
                'description' => '<p>The sanctuary shop offers religious articles, books on the Kibeho apparitions, candles, and locally made crafts. Proceeds support the ongoing mission and maintenance of the sanctuary.</p>',
                'cover_image' => '/images/projects/rwanda-trade-innovation-center/cover.jpg',
                'featured_image' => '/images/projects/rwanda-trade-innovation-center/featured.jpg',
                'gallery' => ['/images/projects/rwanda-trade-innovation-center/gallery-1.jpg'],
                'related_programs' => [],
                'specs' => [
                    'Location' => 'Kibeho, Nyaruguru',
                    'Category' => 'Services',
                    'Items' => 'Devotional articles & books',
                    'Languages' => 'Kinyarwanda, French, English',
                    'Hours' => '8:00 AM – 5:00 PM',
                    'Status' => 'Open Daily',
                ],
                'sort_order' => 4,
            ],
            [
                'slug' => 'meeting-halls',
                'title' => 'Meeting Halls',
                'category' => 'Gathering',
                'year' => '2014',
                'location' => 'Kibeho, Nyaruguru',
                'managed_by' => 'Kibeho Sanctuary',
                'capacity' => '3 halls',
                'status' => 'Available',
                'featured' => false,
                'short_description' => 'Spaces for group catechesis, parish meetings, and retreat sessions during pilgrimage programs.',
                'description' => '<p>Meeting halls of varying sizes accommodate parish groups, youth programs, and retreat facilitators. Audio-visual equipment and seating arrangements can be configured for talks, workshops, and small-group reflection.</p>',
                'cover_image' => '/images/projects/kacyiru-corporate-towers/cover.jpg',
                'featured_image' => '/images/projects/kacyiru-corporate-towers/featured.jpg',
                'gallery' => ['/images/projects/kacyiru-corporate-towers/gallery-1.jpg'],
                'related_programs' => ['Retreats', 'Spiritual Guidance'],
                'specs' => [
                    'Location' => 'Kibeho, Nyaruguru',
                    'Halls' => '3 configurable spaces',
                    'Category' => 'Gathering',
                    'Capacity' => 'Up to 200 per hall',
                    'Equipment' => 'AV & seating',
                    'Status' => 'Available',
                ],
                'sort_order' => 5,
            ],
            [
                'slug' => 'outdoor-prayer-areas',
                'title' => 'Outdoor Prayer Areas',
                'category' => 'Prayer',
                'year' => '2008',
                'location' => 'Kibeho, Nyaruguru',
                'managed_by' => 'Kibeho Sanctuary',
                'capacity' => 'Apparition sites',
                'status' => 'Open Daily',
                'featured' => false,
                'short_description' => 'Sacred outdoor spaces including the apparition hill, Stations of the Cross, and Marian grottos.',
                'description' => '<p>Pilgrims walk the paths of the apparition sites, pray the Stations of the Cross on the hillside, and find quiet corners for personal devotion. These outdoor spaces connect visitors to the very ground where Our Lady of Kibeho appeared.</p>',
                'cover_image' => '/images/projects/musanze-regional-works/cover.jpg',
                'featured_image' => '/images/projects/musanze-regional-works/featured.jpg',
                'gallery' => ['/images/projects/musanze-regional-works/gallery-1.jpg'],
                'related_programs' => ['Rosary', 'Spiritual Guidance'],
                'specs' => [
                    'Location' => 'Kibeho, Nyaruguru',
                    'Category' => 'Prayer',
                    'Sites' => 'Apparition hill, grottos, stations',
                    'Access' => 'Open to all pilgrims',
                    'Guided tours' => 'Available on request',
                    'Status' => 'Open Daily',
                ],
                'sort_order' => 6,
            ],
        ];

        foreach ($facilities as $facility) {
            Facility::updateOrCreate(
                ['slug' => $facility['slug']],
                array_merge($facility, ['is_published' => true])
            );
        }
    }
}
