import {
  Baby,
  Bath,
  Bell,
  BookOpen,
  Bug,
  Bus,
  Car,
  Check,
  ChefHat,
  Church,
  Circle,
  Coffee,
  Fan,
  Flame,
  Headphones,
  Heart,
  Home,
  Map,
  Mountain,
  Plane,
  Presentation,
  Shield,
  Shirt,
  Trees,
  Tv,
  Users,
  UtensilsCrossed,
  Waves,
  Wifi,
  Wind,
  Wine,
  Zap,
  Droplets,
} from 'lucide-react'

const ICONS = {
  parking: Car,
  'secure-parking': Car,
  wifi: Wifi,
  'hot-water': Droplets,
  'hill-views': Mountain,
  garden: Trees,
  'swimming-pool': Waves,
  'table-tennis': Circle,
  bar: Wine,
  restaurant: UtensilsCrossed,
  'restaurant-service': UtensilsCrossed,
  breakfast: Coffee,
  'air-conditioning': Wind,
  fan: Fan,
  generator: Zap,
  'mosquito-nets': Bug,
  'en-suite': Bath,
  tv: Tv,
  kitchenette: ChefHat,
  security: Shield,
  conference: Presentation,
  'conference-service': Presentation,
  chapel: Church,
  'family-rooms': Users,
  balcony: Home,
  wheelchair: Users,
  'bottled-water': Droplets,
  fireplace: Flame,
  playground: Baby,
  laundry: Shirt,
  'daily-mass': Church,
  shuttle: Bus,
  'guided-tours': Map,
  'airport-pickup': Plane,
  'room-service': Bell,
  concierge: Headphones,
  'spiritual-guidance': Heart,
  retreats: BookOpen,
}

export default function LodgingIcon({ id, size = 20 }) {
  const Icon = ICONS[id] || Check
  return <Icon size={size} strokeWidth={1.75} aria-hidden="true" />
}
